/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActiveRequests: typeof import('./src/components/Admin/ActiveRequests.vue')['default']
    AppHeader: typeof import('./src/components/AppLayout/AppHeader.vue')['default']
    Button: typeof import('./src/elements/Button.vue')['default']
    ButtonBar: typeof import('./src/components/User/ButtonBar.vue')['default']
    ButtonItem: typeof import('./src/components/user/ButtonItem.vue')['default']
    copy: typeof import('./src/components/AppLayout/UserLayout copy.vue')['default']
    DashboardLayout: typeof import('./src/components/AppLayout/DashboardLayout.vue')['default']
    Dropdown: typeof import('./src/elements/Dropdown.vue')['default']
    Header: typeof import('./src/components/AppLayout/Header.vue')['default']
    Item: typeof import('./src/components/Admin/Item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleItem: typeof import('./src/components/User/ScheduleItem.vue')['default']
    Sidebar: typeof import('./src/components/AppLayout/Sidebar.vue')['default']
    SIdebar: typeof import('./src/components/AppLayout/SIdebar.vue')['default']
    StateActive: typeof import('./src/components/Admin/StateActive.vue')['default']
    StateBoards: typeof import('./src/components/Admin/StateBoards.vue')['default']
    StateTable: typeof import('./src/components/Admin/StateTable.vue')['default']
    TheAdminActive: typeof import('./src/components/TheAdminActive.vue')['default']
    TheAdminBoards: typeof import('./src/components/TheAdminBoards.vue')['default']
    TheAdminTable: typeof import('./src/components/TheAdminTable.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheUserClient: typeof import('./src/components/TheUserClient.vue')['default']
    UserLayout: typeof import('./src/components/AppLayout/UserLayout.vue')['default']
    VButton: typeof import('./src/elements/VButton.vue')['default']
  }
}
